# Generated by Django 5.2.7 on 2025-12-04 15:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('absent', 'Absent'), ('on-time', 'On time'), ('late', 'Late')], default='absent', max_length=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('student_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='authentication.student')),
            ],
        ),
    ]
