# Generated by Django 5.2.7 on 2025-12-05 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendance',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
