# Generated by Django 5.2.7 on 2025-12-11 02:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0002_alter_studentattendance_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentattendance',
            name='created_at',
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
