# Generated by Django 5.2.7 on 2025-12-11 02:17

import student_attendance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0003_remove_studentattendance_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentattendance',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='timestamp',
            field=models.DateTimeField(default=student_attendance.models.StudentAttendance.default_datetime),
        ),
    ]
