# Generated by Django 5.2.7 on 2025-12-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0004_remove_studentattendance_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
