# Generated by Django 5.2.7 on 2025-12-19 01:39

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0005_studentattendance_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendance',
            name='status',
            field=models.CharField(choices=[('absent', 'absent'), ('on-time', 'on time'), ('late', 'late')], default='absent', max_length=15),
        ),
    ]
