# Generated by Django 5.2.7 on 2025-12-19 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_migrate_student_to_migratestudent'),
        ('student_attendance', '0006_alter_studentattendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='migrate_student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='migrate_attendance', to='authentication.migratestudent'),
        ),
    ]
