# Generated by Django 5.2.7 on 2025-12-19 02:29

from django.db import migrations


def add_migrate_student_id_to_attendance(apps, schema_info):
    StudentAttendance = apps.get_model("student_attendance", "StudentAttendance")
    MigrateStudent = apps.get_model("authentication", "MigrateStudent")

    for attendance in StudentAttendance.objects.all():
        attendance_first_name = attendance.student_id.user.first_name
        attendance_last_name = attendance.student_id.user.last_name
        migrate_student = MigrateStudent.objects.get(
            first_name=attendance_first_name, last_name=attendance_last_name
        )

        attendance.migrate_student_id = migrate_student
        attendance.save()


class Migration(migrations.Migration):

    dependencies = [
        ("student_attendance", "0007_studentattendance_migrate_student_id"),
    ]

    operations = [migrations.RunPython(add_migrate_student_id_to_attendance)]
