# Generated by Django 5.2.7 on 2026-01-10 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0009_remove_studentattendance_student_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentattendance',
            old_name='migrate_student_id',
            new_name='student_id',
        ),
    ]
