# Generated by Django 5.2.7 on 2025-12-08 08:28

import authentication.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='class_section',
            field=models.CharField(default=authentication.models.Classroom.default_section, max_length=50),
        ),
        migrations.AddField(
            model_name='classroom',
            name='grade',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, "class grade can't be below 1"), django.core.validators.MaxValueValidator(6, "class grade can't be above 6")]),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='authentication.classroom'),
        ),
    ]
