# Generated by Django 5.2.7 on 2025-11-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='supervisor',
            field=models.CharField(blank=True),
        ),
    ]
