# Generated by Django 5.2.7 on 2025-12-08 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_classroom_class_section_classroom_grade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='name',
        ),
    ]
