# Generated by Django 5.2.7 on 2025-11-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_classroom_supervisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='qr_url',
        ),
        migrations.AddField(
            model_name='student',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
