# Generated by Django 5.2.7 on 2025-12-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_classroom_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rmt_elligible',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
