# Generated by Django 5.2.7 on 2025-11-03 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_student_qr_url_student_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_room',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.classroom'),
        ),
    ]
