# Generated by Django 5.2.7 on 2025-12-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('teacher', 'teacher'), ('student', 'student'), ('parent', 'parent')], default='student', max_length=20),
        ),
    ]
