# Generated by Django 5.2.7 on 2025-12-19 02:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_student_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrateStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('rmt_elligible', models.BooleanField(default=False, null=True)),
                ('date_of_birth', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('class_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='migrate_student', to='authentication.classroom')),
            ],
        ),
    ]
