# Generated by Django 5.2.7 on 2025-12-19 02:20

from django.db import migrations

def copy_student_to_migrate_student(apps, schema_info):
    Student = apps.get_model('authentication', 'Student')
    MigrateStudent = apps.get_model('authentication', 'MigrateStudent')
    
    for student in Student.objects.all():
        migrate_student_kwargs = {
            'class_room': student.class_room,
            'qr_code': student.qr_code,
            'rmt_elligible': student.rmt_elligible,
            'date_of_birth': student.date_of_birth,
            'first_name': student.user.first_name,
            'last_name': student.user.last_name,
        }
        
        MigrateStudent.objects.create(**migrate_student_kwargs)

class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_migratestudent'),
    ]

    operations = [
        migrations.RunPython(copy_student_to_migrate_student)
    ]
