# Generated by Django 5.2.7 on 2026-01-09 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_migratestudent_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('teacher', 'teacher'), ('parent', 'parent')], default='student', max_length=20),
        ),
    ]
