# Generated by Django 5.2.7 on 2026-01-09 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_myuser_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
