# Generated by Django 5.2.7 on 2026-01-09 03:41

import authentication.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='class_section',
            field=models.CharField(default=authentication.models.Classroom.default_section, help_text="The section identifier (e.g., 'A', 'Bestari', or a random string).", max_length=50),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='grade',
            field=models.IntegerField(default=1, help_text='Primary school grade level (1-6).', validators=[django.core.validators.MinValueValidator(1, "class grade can't be below 1"), django.core.validators.MaxValueValidator(6, "class grade can't be above 6")]),
        ),
        migrations.AlterField(
            model_name='migratestudent',
            name='parent',
            field=models.ForeignKey(blank=True, help_text="Link to a MyUser instance with the 'parent' role.", limit_choices_to={'role': 'parent'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('teacher', 'teacher'), ('parent', 'parent')], default='parent', max_length=20),
        ),
    ]
