# Generated by Django 5.2.7 on 2025-12-19 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_migrate_student_to_migratestudent'),
        ('sahsiah', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sahsiahrecord',
            name='migrate_student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='migrate_sahsiah', to='authentication.migratestudent'),
        ),
    ]
