# Generated by Django 5.2.7 on 2025-12-19 03:06

from django.db import migrations


def add_migrate_to_sahsiah_record(apps, schema_info):
    SahsiahRecord = apps.get_model("sahsiah", "SahsiahRecord")
    MigrateStudent = apps.get_model("authentication", "MigrateStudent")

    for record in SahsiahRecord.objects.all():
        first_name = record.student_id.user.first_name
        last_name = record.student_id.user.last_name
        migrate_student = MigrateStudent.objects.get(
            first_name=first_name, last_name=last_name
        )

        record.migrate_student_id = migrate_student
        record.save()


def reverse_migrate_sahsiah_record(apps, schema_info):
    """This function runs when you migrate backwards."""
    SahsiahRecord = apps.get_model("sahsiah", "SahsiahRecord")
    # Set the field back to None for all records
    SahsiahRecord.objects.all().update(migrate_student_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ("sahsiah", "0002_sahsiahrecord_migrate_student_id"),
    ]

    operations = [
        migrations.RunPython(
            add_migrate_to_sahsiah_record, reverse_code=reverse_migrate_sahsiah_record
        )
    ]
