# Generated by Django 5.2.7 on 2025-12-21 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_migrate_student_to_migratestudent'),
        ('sahsiah', '0003_auto_20251219_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sahsiahrecord',
            name='student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sahsiah', to='authentication.student'),
        ),
    ]
