# Generated by Django 5.2.7 on 2025-12-21 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_migrate_student_to_migratestudent'),
        ('sahsiah', '0004_alter_sahsiahrecord_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sahsiahrecord',
            name='migrate_student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sahsiah', to='authentication.migratestudent'),
        ),
    ]
