# Generated by Django 5.2.7 on 2025-12-21 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sahsiah', '0005_alter_sahsiahrecord_migrate_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sahsiahrecord',
            name='student_id',
        ),
    ]
