# Generated by Django 5.2.7 on 2026-01-10 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sahsiah', '0006_remove_sahsiahrecord_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sahsiahrecord',
            old_name='migrate_student_id',
            new_name='student_id',
        ),
    ]
