# Uses node version 22 as our base image
FROM python:3.10.11

WORKDIR /backend

COPY ./requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN chmod +x ./run.sh

ENTRYPOINT [ "./run.sh" ]

EXPOSE 8080