# Generated by Django 5.2.7 on 2025-12-14 08:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0005_alter_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=256)),
                ('points', models.IntegerField(default=0)),
                ('tag', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DisciplineRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline', to='authentication.student')),
                ('sahsiah_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='record_discipline.disciplinetype')),
            ],
        ),
    ]
