# Generated by Django 5.2.7 on 2025-12-14 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record_discipline', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disciplinerecord',
            old_name='sahsiah_type',
            new_name='discipline_type',
        ),
    ]
