# Generated by Django 5.2.7 on 2025-12-19 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_migrate_student_to_migratestudent'),
        ('record_discipline', '0002_rename_sahsiah_type_disciplinerecord_discipline_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinerecord',
            name='migrate_student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='migrate_discipline', to='authentication.migratestudent'),
        ),
    ]
