# Generated by Django 5.2.7 on 2025-12-19 03:33

from django.db import migrations


def add_migrate_student_id_to_discipline_record(apps, schema_info):
    DisciplineRecord = apps.get_model("record_discipline", "DisciplineRecord")
    MigrateStudent = apps.get_model("authentication", "MigrateStudent")

    for record in DisciplineRecord.objects.all():
        first_name = record.student_id.user.first_name
        last_name = record.student_id.user.last_name
        migrate_student = MigrateStudent.objects.filter(
            first_name=first_name, last_name=last_name
        ).first()
        
        if migrate_student:
            record.migrate_student_id = migrate_student
            record.save()


def reverse_migrate_student_id(apps, schema_info):
    """
    Sets migrate_student_id back to None for all discipline records.
    """
    DisciplineRecord = apps.get_model("record_discipline", "DisciplineRecord")
    # Using .update() is much faster than a loop for reversing data
    DisciplineRecord.objects.all().update(migrate_student_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ("record_discipline", "0003_disciplinerecord_migrate_student_id"),
    ]

    operations = [
        migrations.RunPython(
            add_migrate_student_id_to_discipline_record,
            reverse_code=reverse_migrate_student_id
        )
    ]
