# Generated by Django 5.2.7 on 2025-12-21 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_migrate_student_to_migratestudent'),
        ('record_discipline', '0004_auto_20251219_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinerecord',
            name='migrate_student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discipline', to='authentication.migratestudent'),
        ),
    ]
