# Generated by Django 5.2.7 on 2025-12-25 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record_discipline', '0005_alter_disciplinerecord_migrate_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplinerecord',
            name='student_id',
        ),
    ]
