# Generated by Django 5.2.7 on 2025-12-25 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record_discipline', '0006_remove_disciplinerecord_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disciplinerecord',
            old_name='migrate_student_id',
            new_name='student_id',
        ),
    ]
