# Generated by Django 5.2.7 on 2026-01-04 02:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_discipline', '0007_rename_migrate_student_id_disciplinerecord_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinetype',
            name='points',
            field=models.IntegerField(default=-1, validators=[django.core.validators.MaxValueValidator(-1)]),
        ),
    ]
