# Generated by Django 5.2.7 on 2025-12-09 02:51

import django.db.models.deletion
import rmt.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0005_alter_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RMTRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=rmt.models.RMTRecord.default_datetime)),
                ('updated_at', models.DateTimeField(default=rmt.models.RMTRecord.default_datetime)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.student')),
            ],
        ),
    ]
