# Generated by Django 5.2.7 on 2025-12-09 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rmt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rmtrecord',
            old_name='student',
            new_name='student_id',
        ),
    ]
