# Generated by Django 5.2.7 on 2025-12-19 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_migrate_student_to_migratestudent'),
        ('rmt', '0002_rename_student_rmtrecord_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmtrecord',
            name='migrate_student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='migrate_rmt', to='authentication.migratestudent'),
        ),
    ]
