# Generated by Django 5.2.7 on 2025-12-21 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_migrate_student_to_migratestudent'),
        ('rmt', '0004_auto_20251219_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rmtrecord',
            name='student_id',
        ),
        migrations.AlterField(
            model_name='rmtrecord',
            name='migrate_student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rmt', to='authentication.migratestudent'),
        ),
    ]
