# Generated by Django 5.2.7 on 2025-12-25 22:40

import rmt.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmt', '0005_remove_rmtrecord_student_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rmtrecord',
            name='created_at',
        ),
        migrations.AddField(
            model_name='rmtrecord',
            name='date',
            field=models.DateField(default=rmt.models.RMTRecord.default_datetime),
        ),
    ]
