# Generated by Django 5.2.7 on 2025-12-25 22:40

import rmt.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmt', '0006_remove_rmtrecord_created_at_rmtrecord_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rmtrecord',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='rmtrecord',
            name='timestamp',
            field=models.TimeField(default=rmt.models.RMTRecord.default_datetime),
        ),
    ]
