# Generated by Django 5.2.7 on 2025-12-25 23:11

import rmt.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmt', '0007_remove_rmtrecord_updated_at_rmtrecord_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rmtrecord',
            name='timestamp',
            field=models.DateTimeField(default=rmt.models.RMTRecord.default_datetime),
        ),
    ]
