# Generated by Django 5.2.7 on 2025-12-29 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmt', '0008_alter_rmtrecord_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmtrecord',
            name='is_present',
            field=models.BooleanField(default=False),
        ),
    ]
