# Generated by Django 5.2.7 on 2026-01-09 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rmt', '0009_rmtrecord_is_present'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rmtrecord',
            old_name='migrate_student_id',
            new_name='student_id',
        ),
    ]
