ABSENT_STATUS = ABSENT_STATUS_KEY, ABSENT_STATUS_VALUE = ("absent", "absent")
ON_TIME_STATUS = ON_TIME_STATUS_KEY, ON_TIME_STATUS_VALUE = ("on-time", "on time")
LATE_STATUS = LATE_STATUS_KEY, LATE_STATUS_VALUE = ("late", "late")

ATTENDANCE_STATUS_LOOKUP = {
    ABSENT_STATUS_KEY: ABSENT_STATUS_VALUE,
    ON_TIME_STATUS_KEY: ON_TIME_STATUS_VALUE,
    LATE_STATUS_KEY: LATE_STATUS_VALUE,
}

STATUS_REGEX = "|".join(ATTENDANCE_STATUS_LOOKUP.keys())
