ABSENT_STATUS = ABSENT_STATUS_KEY, ABSENT_STATUS_VALUE = ("absent", "absent")
ON_TIME_STATUS = ON_TIME_STATUS_KEY, ON_TIME_STATUS_VALUE = ("on-time", "on time")
LATE_STATUS = LATE_STATUS_KEY, LATE_STATUS_VALUE = ("late", "late")

STUDENT_ATTENDANCE_STATUS = [
  ABSENT_STATUS,
  ON_TIME_STATUS,
  LATE_STATUS
]