ATTENDANCE_RATE_STATUS_EXCELLENT = "Excellent"
ATTENDANCE_RATE_STATUS_GOOD = "Good"
ATTENDANCE_RATE_STATUS_AVERAGE = "Average"
ATTENDANCE_RATE_STATUS_POOR = "Poor"

ATTENDANCE_RATE_STATUS = [
    ATTENDANCE_RATE_STATUS_EXCELLENT,
    ATTENDANCE_RATE_STATUS_GOOD,
    ATTENDANCE_RATE_STATUS_AVERAGE,
    ATTENDANCE_RATE_STATUS_POOR
]